# Generated by Django 5.1.2 on 2024-11-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('year_level', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('student_id_number', models.CharField(max_length=50)),
                ('committee_name', models.CharField(max_length=100)),
                ('committee_position', models.CharField(max_length=100)),
            ],
        ),
    ]
