# Generated by Django 5.1.2 on 2024-11-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_event_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
