# Generated by Django 5.1.2 on 2024-11-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
